### ISSUE TITLE
[Security] – Limit concurrent Admin sessions to one

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#225]
### Each Admin user should only be bele to open one session

**As a** Admin user of F&E
**I want** to only ever have one session open at any given time
**in order to** so that the system is kept secure

### Scenarios

**Given** I am an Admin user 
**And** I have logged in and started an Admin session on computer 1
**When** I start another logged-in  Admin session on Computer 2
**Then** I should be logged out of the session on computer 1

Not 1: See below for notes from Pen Test

![clogin 1](https://user-images.githubusercontent.com/48209167/61719527-004b2800-ad5d-11e9-804a-166142a92c4f.JPG)

![clogin 2](https://user-images.githubusercontent.com/48209167/61719544-0b9e5380-ad5d-11e9-8dd9-6e556c00e605.JPG)

**Comment by krios82** [comment]
The user will be logged out, but they will only be redirected (and shown the "you've logged in from another browser") the first time they try to do anything on the page.

Other than this, the page will autorefresh after 20 minutes of inactivity.
We can't refresh it more often, because if we do it will keep alive the session and invalidate the session time out mechanism.

**Comment by DFEchristian** [comment]
Closed this issue as it has been released.
