### ISSUE TITLE
Upload Data Elements page - validate that all tabs are included and correctly formatted

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#268]
### When admin user uploads a Data Table, system checks that file contains all expected tabs and that they are correctly formatted

**As a** an F&E Admin user
**I want** to check that the file I am uploading includes all expected, correctly formatted, tabs
**in order to** ensure that I haven't uploaded a partially complete Data Table

### Scenarios

Scenario 1: Missing tab
**Given** I am a admin user who is logged in
**And** I am on the Upload Data Elements from an Excel Data Table page
**And** I have pointed the 'Choose file' option towards an Excel file that is not missing any NPD aliases
**And** the table is missing the  'SC_Addresses_05-06_to_18-19_AUT' tab
**When** I select upload 
**Then** I receive a message that 'The file is missing the following tab or tabs, or they are incorrectly formatted.....'
**And** I see a choice of 'Go Back' or 'Confirm Upload'

Scenario 2: Incorrectly Formatted Tab Name
**Given** I am a admin user who is logged in
**And** I am on the Upload Data Elements from an Excel Data Table page
**And** I have pointed the 'Choose file' option towards an Excel file that is not missing any NPD aliases
**And**  the 'SC_Addresses_05-06_to_18-19_AUT' tab column is formatted 'SCAddresses 05-06 to 18-19 AUT'
**When** I select upload 
**Then** I receive a message that 'The file is missing the following tab or tabs, or they are incorrectly formatted.....'
**And** I see a choice of 'Go Back' or 'Confirm Upload'

Note 1: If more than one tab is missing or badly formatted, display as list
Note 2: Format is...
Note 3: Expected list is.....

**Comment by RICHARDMACHEN1** [comment]
Just tested. The 'go back' functionality doesn't seem to be there

![Data Table Upload](https://user-images.githubusercontent.com/48243847/63590161-f8bcb000-c5a2-11e9-85e7-b558b4887d57.PNG)

I've tried changing the format of the tabs but I'm not getting a message that the tab format is incorrect. I may be doing something wrong though.

Also, the 'last upload' details are incorrect. I did upload that file (see screen shot) but I didn't go through with the upload. I think we need provide details of the last confirmed upload.

![Incorrect upload message](https://user-images.githubusercontent.com/48243847/63590468-ce1f2700-c5a3-11e9-8417-f217021db957.PNG)

@cacquani @DFEchristian @benmemmott We can talk through on Tuesday rather than rush to fix this today.
