### ISSUE TITLE
I see 986 data elements when I click on no category

### ISSUE THREAD

**Issue by DFEchristian** [DFE-Digital/npd-find-and-explore#286]
When I click on categories and search "no category" & click "no category" again I see there are 986 data elements in F&E PROD

[edit] This is a tech task (find out why this happened) and needs no user story.

**Comment by DFEchristian** [comment]
Hi @RICHARDMACHEN1 and @cacquani please can you update the definition/story above?

**Comment by krios82** [comment]
@RICHARDMACHEN1 @benmemmott @DFEchristian 

This happened because two concepts has been deleted, and all their data elements has been moved to the "No Concept" concept.
As the system is now, there's no way to automatically restore the deleted concepts.

To fix this specific situation, we can get the latest uploaded Information Architecture table, find out what concept these data elements belonged to, and restore them manually from the console.

For a more long term fix, we could potentially add a "soft delete" option and a restore page in the system, so that even when someone deletes a concept we will be able to restore it and restore all the data elements that used to belong to that concept.

Please provide feedback on:
1. Should talk with Simone to fix the immediate issue?
2. Do you want the soft delete + restore page to be implemented? (this second part should be a new ticket I think)

**Comment by RICHARDMACHEN1** [comment]
Ooops. I’m guessing this is something I did during my attempts to test? Really sorry if it was me (and I suspect it was) – although I thought I’d only deleted the concepts I’d created.

☹


Richard Machen
Data Modernisation Division, NPD Modernisation Lead, Data Directorate, Operations Group Tel: 07852 151269– Web: www.education.gov.uk<http://www.education.gov.uk/>
Address: 2 St Paul’s Place, Sheffield S1 2JF.
[DfE 2955 Resized for email logo v2]

**Comment by RICHARDMACHEN1** [comment]
@cacquani @benmemmott - yes, lets go ahead with fixing the immediate issue. Is it a case of uploading the Info Arc document and the Data Tables? Would that 're-set' everthimg?

**Comment by RICHARDMACHEN1** [comment]
@cacquani @benmemmott we can add the soft delete into the backlog on a new ticket

**Comment by benmemmott** [comment]
@cacquani @RICHARDMACHEN1 - can do, might need to talk it through though. Shall i put time in with you tomorrow Rich?

**Comment by krios82** [comment]
@RICHARDMACHEN1 
If we upload the Info Arc document (no need to re-upload the data tables) it will reset every manual change you've done this far in production. 
If you're OK with that and you have the latest version of the Info Arc document, you can go ahead and upload it (I only have a very outdated version).

@benmemmott discussing about the long term part you mean?

**Comment by benmemmott** [comment]
@cacquani Yes, about the soft delete story - could be complicated and prob need input of Rich and probably you

**Comment by krios82** [comment]
I've done some further digging, there isn't an Admin user associated with the operation that removed those concepts, but on that day I did some tinkering on Azure and we deployed to production.

My best guess is that the culprit was migration `20190725111338` (add foreign keys to the database), that moved into the "no concept" category all the data elements for which the associated concept no longer existed in the database.

**Comment by RICHARDMACHEN1** [comment]
Cool! Excellent extra digging. Does that change the solution?

Ta

Richard Machen
Data Modernisation Division, NPD Modernisation Lead, Data Directorate, Operations Group Tel: 07852 151269– Web: www.education.gov.uk<http://www.education.gov.uk/>
Address: 2 St Paul’s Place, Sheffield S1 2JF.
[DfE 2955 Resized for email logo v2]

**Comment by DFEchristian** [comment]
This has been superseded by [#309](https://github.com/DFE-Digital/npd-find-and-explore/issues/309) and is now archived.
