### ISSUE TITLE
Detail page – aggregated source list

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#31]
### Detail page shows source for each data item

**As a** researcher
**I want** to see a data item's source
**in order to** understand where the data item came from so I can reference this in my documentation

### Scenarios

Scenario 1 - School Census (Collection and Term)
**Given** I am an anonymous user
**When** I click to view the 'Eligibile for free school meals in the past 6 years' detail page
**And** I view the data item ''SC_Pupil_01-02_to_18-19_AUT.EVERFSM_6_P'
**Then** I see a value of ''Autumn School Census'' in the 'Source' column

Scenario 2 - Annual Collection (Collection)
**Given** I am an anonymous user
**When** I click to view the '?' detail page
**And** I view the data item ''?''
**Then** I see a value of ''?'' in the 'Source' column

BR1: Total list of sources: (?) 

Note 1: In the data tables currently there is 'Source' or 'Collection Term'. They are not all populated. So this will require more work in the 'Enhance Data Tables' category.

Note 2:  How do we accomadate School Checking Exercise - this is potentially a collection in its own right. (Ryan originally suggested not including it, or KS4 Attainment)

**Comment by benmemmott** [comment]
![31](https://user-images.githubusercontent.com/48209167/54424578-1b50c000-470b-11e9-97ed-c1ae6971d432.JPG)

**Comment by spikeheap** [comment]
This information isn't currently held in the Data Tables. I think we mean:

> The point at which the data element was collected

It *looks* like we mean "which sheet in the Data Tables does this come from", but that's not accurate because some data elements are copied from another source, for example `FSM_6` in `KS2_Pupil` is copied from the School Census, before going through the School Checking Exercise. This is likely different to the attainment data in `KS2_Pupil`, which comes from awarding bodies and also goes through the School Checking Exercise.

@jonrhodespaper / @RICHARDMACHEN1 / @petelonsdale we need to think about what we mean by this, and in particular what we'd expect to see for awarding data and other tabs on the Excel Data Tables (for example CIN/CLA).

**Comment by spikeheap** [comment]
This looks like we can extract it from FbAY, so this is blocked pending the investigation into loading that file

**Comment by benmemmott** [comment]
Edited to combine two other archived stories - 36 and 40 - following discussions today. Will need to remove code that supports ''Collection Term'' as this is less useful than source, detailed here.
