### ISSUE TITLE
No results when querying the 'data_table_rows' databae table

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#345]
Within the database table 'data_table_rows' there seems to be no data present in that table.

when I query the table by selecting the first 100 rows for example:

SELECT * FROM public.data_table_rows
ORDER BY id ASC LIMIT 100

...there is no data within the results.

**Comment by DFEchristian** [comment]
Will speak to Cristina re this.

**Comment by krios82** [comment]
That’s perfectly likely, the `data_table_rows` is a new table that is used for support during data tables upload and when an upload gets aborted all its related `data_table_rows` elements get cleared.
Same with `data_table_tabs`.
`data_table_uploads` has been renamed from the old table that used to hold the successfully uploaded data tables, so that may have elements from before the renaming.
